### ISSUE TITLE
An f-droid release? :)

### ISSUE THREAD

**Issue by kuba-orlik** [wizmer/syncorg#10]
Hi! I'd like to check out the app, but I don't have Google Play Services. Could you provide the built `.apk` as a part of the GitHub "release" or (better yet) publish the app on [F-Droid](https://f-droid.org/)? :)

**Comment by wizmer** [comment]
Release added here: https://github.com/wizmer/syncorg/releases/tag/2.0.3
and F-Droid request done ;-)

**Comment by kuba-orlik** [comment]
Thank you! :)

**Comment by Dragnucs** [comment]
On f-droid [submission](https://f-droid.org/forums/topic/syncorg/) they say that the project

> Uses an immense amount of jar files
> 
> These need to be removed before the app can be part of fdroid.

Would the be solved?

**Comment by gdt** [comment]
I suspect the jar issue is that f-droid wants to build from source, and a build process with already-built jars checked into git isn't entirely a build from sources.

Separately, I have the impression that syncorg might use some of the non-free Google APIs and e.g. I'm unclear on whether the dropbox api is Free Software.   f-droid builds often just drop non-free dependencies.

**Comment by wizmer** [comment]
Hi, 

I am actually clueless as well about what has to be removed. I removed all the existing jars from the project (that were useless by the way) but there still exists some dependancies through Gradle and Maven. I don't know if this a problem or not. I'll try to resubmit the app to F-Droid this week.
