### ISSUE TITLE
should we add "Github" "gitlib" and some other ssh sync method?

### ISSUE THREAD

**Issue by tumashu** [wizmer/syncorg#13]

**Comment by wizmer** [comment]
SyncOrg already support GitHub. What do you mean ?

**Comment by tumashu** [comment]
Add a "github" lable, so we can input account  passwd and rep to config a sync

**Comment by flyck** [comment]
Could I get a glance at a working github config? I cant seem to get it working alone.
absolute path: git@github.com:BubblesToTheLimit/org-gtd.git
host: www.github.com/BubblesToTheLimit
Port: 22

**Comment by wizmer** [comment]
Hi & sorry for the late reply

Username: git
Absolute path: BubblesToTheLimit/org-gtd.git
Host: github.com
Port: 22 (or let blank)

You need to add the generated DSA key to your public account before clicking OK.

Hope this helps
