### ISSUE TITLE
org.eclipse.jgit.api.errors.TransportException ECONNREFUSED with wrong port reported

### ISSUE THREAD

**Issue by jackjackk** [wizmer/syncorg#15]
I'm trying to setup an ssh connection as suggested when the app is launched for the first time.
Even though the setup parameters seem correct, I get the error in the title, with port 22 reported in the error message. It looks like the number I wrote under "Port" was not taken into consideration. Are non-standard ssh port numbers working? 

Thanks,

Giacomo

**Comment by wizmer** [comment]
Indeed, there was a bug. It should be fixed for tomorrow's release.
