### ISSUE TITLE
ownCloud/nextCloud support

### ISSUE THREAD

**Issue by Dragnucs** [wizmer/syncorg#19]
Please add a way to sync org files vias ownCloud or nextCloud.

**Comment by alraban** [comment]
This would be excellent. Even generic webdav support like mobileorg has would work fine, as that would sweep in owncloud/nextcloud and many more services.

**Comment by gour** [comment]
> ...generic webdav support like mobileorg has...

I'm looking for Android sync client considering either SyncOrg or Orgzly, but wonder whether old mobileorg's webdav support is still functional since it looks that WebDAV is not the top priority for SyncOrg and I want to avoid using services like Dropbox/GoogleDrive etc.?
