### ISSUE TITLE
Local filesystem sync

### ISSUE THREAD

**Issue by edrex** [wizmer/syncorg#23]
Not sure which repo I should be reporting issues to. I have Syncthing syncing my Documents to android, so I'd like to have SyncOrg sync with a specified folder on the SD Card.

https://github.com/matburt/mobileorg-android/issues/494

**Comment by wizmer** [comment]
I am actually working on it these days but it appears it is more complex than expected. I hope to release this new feature before the end of the month.

**Comment by edrex** [comment]
thanks @wizmer, LMK if I can help with any early testing (i have android studio etc)

**Comment by wizmer** [comment]
Hi @edrex !
I am done with the external synchronization but my personal phone does not support SD cards so I can't test them. If you are still willing to help give me your email address and I'll add you to the SyncOrg Beta testing program.

**Comment by edrex** [comment]
_sent email_
