### ISSUE TITLE
New and edited entries end up double in Todos and Agenda view

### ISSUE THREAD

**Issue by Emilv2** [wizmer/syncorg#26]
I'm using version 2.0.5 from F-Droid, starting without sync and an empty folder. When I add a new entry, it ends up twice in the Todos list
![258573587](https://cloud.githubusercontent.com/assets/15071778/21285221/283c4278-c3f8-11e6-844b-35fb330cfd53.jpg)
![1758107630](https://cloud.githubusercontent.com/assets/15071778/21285234/5cc93c26-c3f8-11e6-8307-aadfd9a1b058.jpg)
When I edit the entry, the old entry stays in the Todos list, and two new entries are added.
![2134569680](https://cloud.githubusercontent.com/assets/15071778/21285247/ead6bb74-c3f8-11e6-9c36-a9958001fa01.jpg)
![1275408914](https://cloud.githubusercontent.com/assets/15071778/21285250/f2c9fd8c-c3f8-11e6-992f-556ffc5f3b9e.jpg)
Something similar happens to the Agenda view, this is how the agenda view looks like with the same one entry in my test.org file after adding, removing and editing some entries.
![2134569680](https://cloud.githubusercontent.com/assets/15071778/21285280/a02012f0-c3f9-11e6-8e84-b6902932b7ca.jpg)

![421245686](https://cloud.githubusercontent.com/assets/15071778/21285275/8cf493ae-c3f9-11e6-9f1e-ca98ad7cc4b8.jpg)
![817361721](https://cloud.githubusercontent.com/assets/15071778/21285276/910190f0-c3f9-11e6-922f-ffe317dbcc70.jpg)
![2095662738](https://cloud.githubusercontent.com/assets/15071778/21285279/94edf1b8-c3f9-11e6-86df-73a9a76de0a6.jpg)

**Comment by barryWarnock** [comment]
I'm having a similar issue where when I sync some todos or agenda items get duplicated.

**Comment by sokolgeo** [comment]
Same here. Set up only local folder, no synchronization.

Still getting duplicate records in todo and agenda.

This happens also with latest app version 2.0.5.2

On a side not - this might have something to do with synchronization. Despite being "local file only" there seems synchronization icon appearing for split second anyways - and then duplicates appear.

Another observation - this may something to do with scheduled dates. For duplicate records I in duplicates wrong <SCHEDULED> date. Original item has <SCHEDULED> = 09.01.2017 and duplicate records have 09.02.2017 (+1 month) displayed in their properties.

Hope it helps.

**Comment by schuach** [comment]
Same here. SyncOrg 2.0.5.1 on Android 6.0
New duplicates are created every time I open the Todo or Agenda view -- even when the entry was not edited.

**Comment by wizmer** [comment]
Fixed. It was indeed related to a bug in the synchronization.
