### ISSUE TITLE
Check if file to parse is actually a directory

### ISSUE THREAD

**Issue by shackra** [wizmer/syncorg#30]
I have a directory inside my directory with all my org files, the software stops parsing the files due to erroneously trying to parse a directory.

**Comment by wizmer** [comment]
Thx for the feedback. Can you tell me if you are using the Git synchronization or the external one ?

**Comment by elzorrorebelde** [comment]
I'm using the later as I have Syncthing on my phone and laptop 

El 4 de enero de 2017 17:10:47 GMT-06:00, Benoit Coste <notifications@github.com> escribió:
>Thx for the feedback. Can you tell me if you are using the Git
>synchronization or the external one ?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/wizmer/syncorg/issues/30#issuecomment-270514380

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by wizmer** [comment]
That's what I thought. Then it is fixed in the upcoming version.
