### ISSUE TITLE
Is sync with a Git repo implemented yet?  If so, how do I configure that?

### ISSUE THREAD

**Issue by nelljerram** [wizmer/syncorg#40]
I keep my org files in a private repo on bitbucket, so it would be wonderful I could configure SyncOrg to use that.  But it's not clear to me if this is implemented yet, or if so how to configure it.

**Comment by nelljerram** [comment]
(BTW, I'm happy to help with coding if you can point me in the right direction.)

**Comment by wizmer** [comment]
Ahah, funny that you post this the day gitlab.com is down (a bad rm - rf
from what I've heard) but yes it is supposed to work.
1) Go to the setup wizard
2) Choose 'SSH server'
3) Click help and look at the second example (the one with github) to set
up the correct parameters.

**Comment by nelljerram** [comment]
Thanks @wizmer, and sorry to take so long to follow up. 

Those help instructions seem clear, but I find that when I press the PARENT FOLDER button, SyncOrg crashes. This is with version 2.0.5.3, and I should perhaps mention that I'm running on a Blackberry Classic. The Classic has an Android runtime, but of course it's possible that it has bugs that are different from a more standard Android. 

Any thoughts? Do I perhaps need newer than 2.0.5.3?

**Comment by FHulot** [comment]
Found this workaround to that problem on 2.0.5.3 running on LineageOS 7.1.1

Using a file manager, create a folder in your home directory on the internal SD. For example SyncOrg.

When setting up the parent folder, select "create folder" and create a subfolder to the one you just created using the file manager. Use the full path. Mine was

/storage/emulated/0/SyncOrg/foo

Use the back button to go back one directory level. "foo" will be listed, indicating that what you think is happening is really happening.

Click "select folder", making /storage/emulated/0/SyncOrg the parent folder.

Using this, I was able to go on to the next step and connect to a git repo on a local computer via SSH.

I don't know if creating the "foo" directory level is really necessary. I deleted it later.

**Comment by nelljerram** [comment]
Thanks @FHulot, I will try this out.

In the bigger picture, though, I discovered in the meantime that the Blackberry Classic's Android runtime is Jelly Bean (4.3).  So it's possible that there are many other problems lurking, because of that runtime being so old, and that it is simply unrealistic to expect SyncOrg to be able to work with that.

**Comment by wizmer** [comment]
4.3 should normally work. In fact, if you see any app on the Play Store it means that it is supposed to be supported on your phone.
In fact in SyncOrg's case, old Android versions have less problems as they are less stringent about permissions (I don't say it is a good thing).

**Comment by nelljerram** [comment]
Thanks @wizmer, that's interesting, and will be useful if I return to this approach.  (Instead, for now, I've been using another todo list app on my phone, and have found that it's simple for me to manually merge items from that into my master org setup.)
