### ISSUE TITLE
Query about Android SDK version

### ISSUE THREAD

**Issue by nelljerram** [wizmer/syncorg#41]
https://github.com/wizmer/syncorg/wiki/Contributing says "Install Android 6 API 24 if you haven't already: Go to File -> Settings and search for "Android SDK", check "Android6.0 (Marshmallow)" and click apply."

But my Android SDK install says that
- API 24 is Android 7.0 (Nougat)
- API 23 is Android 6.0 (Marshmallow)

Can you check which is the correct version for SyncOrg?

**Comment by knezi** [comment]
API 24 works for me. You might be missing BuildTools 24.0.1.

**Comment by wizmer** [comment]
Indeed, there was a typo in the wiki. I fixed it.
It should be API 24 is Android 7.0 (Nougat)
